### ISSUE TITLE
An error about GLFW

### ISSUE THREAD

**Issue by Harry-mic** [yardenas/la-mbda#5]
Hello,dear authors of lambda!
We have meet a strange problem when we first finished my pip3 install . ,and run the commend on the server as you suggested:
`python3 experiments/train.py --log_dir results/la_mbda/point_goal2/314 --environment sgym_Safexp-PointGoal2-v0 --total_training_steps 1000000 --safety`

There exists a 'GLFWError' as the follows:
`GLFWError: (65544) b'X11: Failed to open display :1'`

Then ,the tqdm began and suddenly shut down at 0%. After that ,there come another problem about GLFW:
` GLFWError: (65537) b'The GLFW library is not initialized'`.The whole process is then shut down.

We run the code on the server without any display device. So i wonder if the problem comes from the lack of the display as the GLFW is strongly related to 3D graph. Also,we'd appreciate if you can tell us how to run the code on a server without a display device!

**Comment by yardenas** [comment]
Yes, GLFW doesn't work on headless machines (as par https://github.com/deepmind/dm_control). 

I guess you are running the code on a headless machine with a GPU. If that's the case, I suggest the following:
- Make sure you have [GLEW](https://github.com/nigels-com/glew) installed on your server.
- Before running the code, make sure to set the `MUJOCO_GL` environment variable to `egl`. That signals deepmind control suite to render with GLEW instead of GLFW.

Let me know if it didn't work out.

Good luck with your experiments! :mushroom:

**Comment by Harry-mic** [comment]
Thanks for your carefully explaination!
I try to search the interface of the MUJOCO_GL, but I fail. So I wonder if the setting can be set in the configs or it shall be put directly before the train code in 'train.py' , like:

`if __name__ == '__main__':`
    `    config = train_utils.make_config(train_utils.define_config())`
    `    from la_mbda.la_mbda import LAMBDA`
    `    MUJOCO_GL="egl"`
    `    train_utils.train(config, LAMBDA)`

**Comment by Harry-mic** [comment]
I have solved this error，thanks for your help！
I just add :
`import os`
`os.environ['MUJOCO_GL'] = 'egl'`
and it works perfectly!

**Comment by yardenas** [comment]
Great! Nice that you could solve it.
