### ISSUE TITLE
About the observation.

### ISSUE THREAD

**Issue by Zarzard** [yardenas/la-mbda#6]
Congratulations! I think LAMBDA is a pretty good work!
I wonder if you have tested LAMBDA in tasks with sensor-based observations, instead of the pixel-based ones used in the paper.

**Comment by yardenas** [comment]
Hi @Zarzard!

Thanks for reaching out! I haven't tried it with sensor-based observation but I think it shouldn't be that hard to try. The idea is to replace the CNN encoder and decoder in [`World Model`](https://github.com/yardenas/la-mbda/blob/master/la_mbda/models.py) with dense layers. I think it should definitely work, with the main gotcha being normalizing the observations to be between [-1, 1].

Feel free to make a PR with that, we can try it out if you want!

**Comment by Zarzard** [comment]
Thanks for the response! It will be very nice for you to provide the sensor-based results!

**Comment by yardenas** [comment]
Yes, I agree but I'm working on other projects now. If you feel like contributing this, I'd be happy to accompany you with a PR.

Closing for now.

**Comment by Zarzard** [comment]
Okay, I'll try myself then. Thanks!

**Comment by aagha6** [comment]
@yardenas Thanks for sharing the code! 
I want to use LAMBDA on sensor observations instead of images, and I was a bit confused by this issue. If I understand correctly, the code already uses an MLP as an encoder/decoder for the observations if the observation type is set to "dense" [here](https://github.com/yardenas/la-mbda/blob/542df63fb3ab5712185644d07ca2968faa6f76fe/la_mbda/building_blocks.py#L20), right?
